<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<PackageId>projectFrameCut.Drawing</PackageId>
		<Product>the true core of projectFrameCut</Product>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.45">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<ProjectReference Include="..\projectFrameCut.Drawing.Base\projectFrameCut.Drawing.Base.csproj" PrivateAssets="all" />
		<ProjectReference Include="..\projectFrameCut.Drawing.Effect\projectFrameCut.Drawing.Effect.csproj" PrivateAssets="all" />
		<ProjectReference Include="..\projectFrameCut.Drawing.Processing\projectFrameCut.Drawing.Processing.csproj" PrivateAssets="all" />
		<ProjectReference Include="..\projectFrameCut.Drawing.Text\projectFrameCut.Drawing.Text.csproj" PrivateAssets="all" />
		<ProjectReference Include="..\projectFrameCut.Drawing.Vector\projectFrameCut.Drawing.Vector.csproj" PrivateAssets="all" />

		<PackageReference Include="System.IO.Hashing" Version="10.0.8" /> <!-- for the Base project, make sure it's included in dependencies -->
			
	</ItemGroup>

</Project>
