<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<PackageId>projectFrameCut.Drawing.Effect</PackageId>
		<Description>projectFrameCut Drawing library - advanced image effects</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\projectFrameCut.Drawing.Base\projectFrameCut.Drawing.Base.csproj" />
  </ItemGroup>

</Project>
